machow/siuba

siuba/siu.py
siuba/tests/test_siu.py

e.g. `_.a[_.b:_.c]`
```
█─[
├─█─.
│ ├─_
│ └─'a'
└─█─'__call__'
├─<class 'slice'>
├─█─.
│ ├─_
│ └─'b'
├─█─.
│ ├─_
│ └─'c'
└─None
```

siu: convert slices to calls

---

docs/api_table_core/01_filter.Rmd
docs/api_table_core/02_arrange.Rmd
docs/api_table_core/03_select.Rmd
docs/api_table_core/04_rename.Rmd
docs/api_table_core/05_mutate.Rmd
docs/api_table_core/06_transmute.Rmd
docs/api_table_core/07_summarize.Rmd
docs/api_table_core/08_group_by.Rmd
docs/conf.py
docs/index.rst
siuba/dply/forcats.py

Adds examples and narrative for core 1 table verbs

docs: complete for core 1 table verbs

---

siuba/dply/verbs.py
siuba/sql/verbs.py
siuba/tests/test_verb_count.py

```
In [1]: from siuba.data import mtcars                                                    
In [2]: from siuba import count                                                          
In [3]: count(mtcars)                                                                    
Out[3]: 
n
0  32
In [4]: count(mtcars, wt = "hp")                                                         
Out[4]: 
n
0  4694
```

feat: count with no groups is like one big group

---

examples/examples-dplyr-funcs.ipynb
siuba/dply/verbs.py

fix: pandas - arrange correctly resets index

---

LICENSE
setup.py

Change license mit

---

examples/examples-dplyr-funcs.ipynb
siuba/dply/verbs.py
siuba/sql/verbs.py
siuba/tests/test_verb_transmute.py

feat: sql implement transmute, add tests

---

siuba/dply/vector.py
siuba/dply/verbs.py
siuba/sql/verbs.py
siuba/tests/test_verb_join.py

Fix semi join

---

siuba/dply/verbs.py
siuba/tests/test_verb_separate.py

Feat pandas separate, extract, unite

---

siuba/sql/verbs.py
siuba/tests/test_sql_misc.py

Implements a `sql_raw` function, that allows you to insert a raw SQL string into your query.
addresses #80

Feat raw sql

---

.travis.yml
setup.py

I don't know what was up with the travis build breaking across the board, but not testing against dev python versions fixed it...

Fix install no postgres

---

siuba/experimental/pd_groups/dialect.py
siuba/tests/test_dply_series_methods.py

fix: fast_summarize, along with methods tests

---

siuba/experimental/pd_groups/dialect.py
siuba/experimental/pd_groups/test_pd_groups.py

Feat pd groups validation

---

siuba/tests/helpers.py

```python
from siuba.tests.helpers import data_frame
data_frame(a = [1,2,3],  _index = [4,5,6])
```

tests: data_frame helper now takes _index argument

---

siuba/tests/test_siu.py

Should add the final test for #84

tests: siu explain can roundtrip a method call

---

siuba/experimental/pd_groups/dialect.py
siuba/experimental/pd_groups/translate.py
siuba/siu.py
siuba/spec/series.yml
siuba/tests/test_dply_series_methods.py

feat: fast pd grouped methods allow dim 0 properties, like dtype

---

siuba/sql/verbs.py
siuba/tests/test_verb_summarize.py

Fix sql summarize subqueries

---

Makefile
docs/developer/index.rst
siuba/dply/vector.py
siuba/experimental/pd_groups/dialect.py
siuba/experimental/pd_groups/groupby.py
siuba/experimental/pd_groups/test_pd_groups.py
siuba/experimental/pd_groups/translate.py

* Exposes generic functions for fast grouped operations
* Cleans up code a big
* Adds module level docs
I thought I had merged this in already! Going to merge now, and then take a pass over documentation after merging #308!

Refactor fast groups

---

.github/workflows/ci.yml

Adds test deployments for releases starting with TEST

ci: add test deployment to action

---

.github/workflows/ci.yml

addresses #387 . Note that I should set netlify to point to siuba.org/docs. (or siuba.org for now)

feat(ci): publish main branch docs to netlify

---

siuba/meta_hook.py

chore: deprecation warning in metahook

---

siuba/dply/verbs.py
siuba/tests/test_verb_head.py

feat: head over grouped data

---

docs/intro.Rmd

This PR updates imports to reflect what is used in the example.

update import for plotnine example

---

.github/workflows/ci.yml

* Adds a wheel build to release step in CI

ci: add wheel build to release

---

siuba/sql/utils.py
siuba/sql/verbs.py
siuba/tests/test_verb_show_query.py

* modifies behavior for simplify option of show_query() with SQL, to use a `*` in the select clause when possible.
TODO: articulate the rules

Feat simplify query
