machow/siuba

- siuba/dply/verbs.py
- siuba/sql/verbs.py
replaces all wrapped funcs that are named using `def _():`, with `def _func_name()`. So mutate now wraps `def _mutate():`
> clarify stacktraces by naming wrapped funcs

- examples/examples-postgres.ipynb
- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/test_sql_verbs.py
* remove now unnecessary cases of `strip_symbolic` from verb defs (handled in dispatcher)
* LazyTbl has `__repr__` method, giving data preview
* fix and test sql group_by func
> Clean and polish

- .travis.yml
- Makefile
- docker-compose.yml
- examples/examples-postgres.ipynb
- requirements.txt
- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/conftest.py
- siuba/tests/helpers.py
- siuba/tests/test_dply_verbs.py
- siuba/tests/test_sql_verbs_distinct.py
* set up basic infrastructure for testing with sqlite, and postgres
* test distinct verb. some fixes..
- when no variables given, applies distinct to all variables (before produced error)
- _keep_all raises error for SQL, unless no vars specified
* added sqlite and postgres tests to travis-ci
> Feat sql tests

- siuba/dply/verbs.py
- siuba/tests/test_verb_join.py
* implements pandas anti_join (solves #79)
* fixes semi join including joining columns for right table, when on argument was a mapping (e.g. `semi_join(DF1, DF2, on = {'a': 'b'})` including 'b' column)
* fixes pandas full_join (was expecting the word "outer)
> Feat pd anti join

- siuba/tests/conftest.py
- siuba/tests/test_verb_join.py
setting autouse = True meant that each test ran three times, once for each backend. However, this means that tests that don't even use backends just are re-run three times :/
> fix: pytest skip_backend fixture running too often

- siuba/error.py
- siuba/siu.py
- siuba/sql/verbs.py
- siuba/tests/test_error.py
- siuba/tests/test_sql_verbs.py
The only application so far is removing context from stacktraces, when SQL can't find a function translation:
I think we can do some work to shorten the stack traces a bit further, by catching warnings that are for users, rather than developers in the dispatch function, but this is pretty good for now!
> feat: ShortException error, and shortened sql error stack traces

- examples/examples-dplyr-funcs.ipynb
- siuba/dply/verbs.py
- siuba/tests/test_verb_spread.py
addresses 
* #88 - allow var select style arguments (e.g. _.column_name)
* #89 - spread can take a grouped data frame
> Fix spread feature parity

- siuba/dply/verbs.py
- siuba/tests/test_dply_verbs.py
In addition tests, that arrange resets index (which was already implemented), so addresses #85
> fix: pandas arrange, filter now always resets index

- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_mutate.py
Addresses #41 
Consolidated with the function col_expr_requires_cte! Now is much better at not creating extra ones :)
```
SELECT anon_1.id, anon_1.user_id, anon_1.email_address, anon_1.id2, anon_1.id2 + 1 AS id3a, anon_1.id2 + 2 AS id3b 
FROM (SELECT addresses.id AS id, addresses.user_id AS user_id, addresses.email_address AS email_address, addresses.id + 1 AS id2 
FROM addresses) AS anon_1
```
This PR passes all tests, but I might look for a few edge cases before merging...
> feat: sql mutate uses fewer CTEs

- .gitignore
- Makefile
- docs/developer/index.rst
- docs/developer/pandas-group-ops.Rmd
- docs/developer/sql-translators.ipynb
- examples/architecture/003-fast-mutate.ipynb
- siuba/dply/verbs.py
- siuba/experimental/pd_groups/__init__.py
- siuba/experimental/pd_groups/dialect.py
- siuba/experimental/pd_groups/groupby.py
- siuba/experimental/pd_groups/test_pd_groups.py
- siuba/experimental/pd_groups/translate.py
- siuba/siu.py
- siuba/spec/series.py
- siuba/spec/utils.py
- siuba/sql/verbs.py
- siuba/tests/conftest.py
- siuba/tests/helpers.py
- siuba/tests/test_dply_series_methods.py
- siuba/tests/test_dply_verbs.py
- siuba/tests/test_verb_summarize.py
**Features**
* Implementation of fast mutate, filter, and summarize using CallTreeLocal (#134)
* fixed current grouped pandas mutate to preserve row order (#139)
* laid down tests of all supported series methods, currently skipping SQL backends (but ready to go!)
* put up some very basic documentation (#145)
* wrote an ADR on the rational for fast groupby (#135)
Note that CallTreeLocal has new options, allowing it to look up based on chained attributes (e.g. look for an entry named "dt.year", and override custom function calls.).
I still need to finish support for user defined operations and some light siu refactoring.
**Breaking changes**
* Removed the rm_attr argument from CallTreeLocal, since converting subattrs like `dt.year` will consume `dt` anyway (can't imagine a situation where …
> Fast mutate

- siuba/siu.py
- siuba/sql/verbs.py
- siuba/tests/test_siu.py
Fixes regression where SQL translations for `str` accessor methods don't remove the `str` portion. Adds tests to avoid this the future.
> fix CallTreeLocal not removing sub_attr from method calls

- .travis.yml
- requirements.txt
- setup.py
This adds python 3.8 to travis, and provides explicit dependency support.
Addresses #154 #161
> tests: add python 3.8 to travis

- docs/generate_impl_table.Rmd
- siuba/experimental/pd_groups/groupby.py
- siuba/experimental/pd_groups/translate.py
- siuba/spec/series.py
- siuba/sql/dialects/postgresql.py
- siuba/sql/utils.py
- siuba/tests/test_dply_series_methods.py
This PR makes the following changes to the ad-hoc spec I've been using for characterizing grouped DataFrame methods.
* change things like `xfail = ['postgres']` to `postgres = 'xfail'`.
* make corresponding changes to test files
* clean up unit tests over spec, extend its coverage (which used only mutate) to also test summarize
The last piece I will include before merging is a table in the docs, showing which methods are supported as...
* in fast grouped methods
* in postgres
> [WIP] Refactor pd grouped

- siuba/dply/forcats.py
enables the following.
```python
from siuba.dply.forcats import fct_lump
fct_lump(['a', 'a', 'b', 'b', 'c', 'd'], prop = .2)
```
output:
```
[a, a, b, b, Other, Other]
Categories (3, object): [b, a, Other]
```
> feat: add prop arg to fct_lump

- siuba/sql/verbs.py
- siuba/tests/test_verb_join.py
addresses #200 (and apparently works in sqlite?!)
Here is a sort of cumbersome example.
```python
import pandas as pd
from sqlalchemy import create_engine
from siuba.sql import LazyTbl
from siuba.data import mtcars
engine = create_engine("sqlite:///:memory:")
mtcars[["cyl", "mpg"]].to_sql("mtcars", engine, if_exists = "replace", index = None)
bounds = pd.DataFrame({'lower': [5, 6], 'upper': [6, 8]})
bounds.to_sql("bounds", engine, if_exists = "replace", index = None)
tbl_mtcars = LazyTbl(engine, "mtcars")
tbl_bounds = LazyTbl(engine, "bounds")
from siuba import inner_join, collect, show_query
q = inner_join(
tbl_mtcars,
tbl_bounds,
sql_on = lambda lhs, rhs: lhs.cyl.between(rhs.lower, rhs.upper)
)
show_query(q, simplify = True)
```
SQL output:
```SQL
SELECT anon_1.cyl, anon_1.mpg, …
```
> feat: sql support custom join conditions via sql_on

- siuba/experimental/pd_groups/dialect.py
- siuba/experimental/pd_groups/translate.py
- siuba/spec/series.py
- siuba/tests/test_dply_series_methods.py
This PR completes the spec of series methods, but marking unimplemented method with either Todo, Maydo, or Wontdo. This means that every method or property--except for accessors, like str--are included. Likely, they should also be included, but it's not a big deal for now.
Once this is in, I can prioritize using this spec alone to generate the table of supported methods:  https://github.com/machow/siuba-doc-method-table
> feat: full series spec, with unimplemented methods

- siuba/dply/verbs.py
- siuba/siu.py
- siuba/spec/series.py
- siuba/spec/utils.py
- siuba/tests/test_siu.py
Addresses #131
Resolves the following issues, by disabling their methods on the `Symbolic` object:
```python
from siuba import _
next(iter(_))
for ii in _: pass
'a' in _
_.a.source
```
Note that this brings the symbols behavior strongly in line with numpy arrays and pandas series
> fix: siu no longer falsey, iterable, and uses hidden properties

- siuba/experimental/datetime.py
- siuba/tests/test_dply_datetime.py
Adds two new single dispatch functions: floor_date() and ceil_date(). These are put in experimental for now.
```python
from siuba.experimental.datetime import floor_date, ceil_date
import pandas as pd
import pandas as pd
a_date = "2020-02-02 02:02:02"
dti = pd.DatetimeIndex([a_date])
floor_date(dti, "MS")
#DatetimeIndex(['2020-02-01'], dtype='datetime64[ns]', freq=None)
floor_date(dti, "M")
#DatetimeIndex(['2020-01-31'], dtype='datetime64[ns]', freq=None)
```
> Feat floor date

- docs/_static/custom.css
Moves sidebar from the top, to the bottom of page on mobile
big ups to @bakera81 for catching 😅
> docs: fix sidebar on top for mobile

- siuba/dply/verbs.py
- siuba/tests/test_verb_summarize.py
> fix: pandas summarize validate len, use Series arrays

- .travis.yml
Small change so I can test siuba everyday on travis for this case: user pip installs siuba with latest dependencies. This means it will test against pandas versions the day they are released. I set it to only run on the "latest" branch, so that tests run on other branches are only those using specified versions for requirements.
> tests: travis-ci only tests latest deps on latest branch

- siuba/dply/forcats.py
A cure for the sadness felt by fct_collapse raised in #124 
```python
import pandas as pd
from siuba.dply.forcats import fct_collapse
test = pd.Series(['Hip-Hop/Rap', 'East Coast Rap', "Gangsta Rap", None])
fct = fct_collapse(test, {'Hip-Hop/Rap': ['East Coast Rap', "Gangsta Rap"]})
fct
```
> fix: fct_collapse preserves missing values

- siuba/dply/verbs.py
- siuba/tests/test_verb_join.py
e.g. this type on argument always failed: `anti_join(table1, table2, on = "some_key")`
> fix: pandas anti-join breaks when on is string

- siuba/sql/verbs.py
- siuba/tests/test_verb_filter.py
- siuba/tests/test_verb_join.py
addresses #276, and a gnarly issue introduced recently, where multiple conditions in a filter produced multiple FROM clauses that didn't work, rather than a chain of subqueries (how siuba operates).
The filter issue was caused because it attempts to swap in the right table into a sql operation using sqlalchemy's ClauseAdapter. However, because the original select object was being mutated, I don't think sqlalchemy recognized the columns used prior to the mutation as coming from the "same" object. This meant it didn't swap them out for the aliased version of the select.
As a result, both the unaliased and aliased select statements were used:
```sql
SELECT anon_1.cyl, anon_1.mpg, anon_1.hp 
FROM 
-- first clause w/ table alias
(SELECT anon_2.cyl AS cyl, anon_2.mpg AS mpg, anon_2.hp AS hp, …
```
> fix: sql join order by fix, filter multiple args fix

- siuba/sql/verbs.py
- siuba/tests/test_verb_join.py
Noticed while implementing https://github.com/machow/funneljoin-py. The gist is that sqlalchemy doesn't have a right join option. To do a right join, you switch the things being joined. Siuba did this, but did not switch them back, which caused issues with (1) using the wrong suffixes, (2) behaviors that keep the correct grouping column, e.g. the right key column in this case.
> fix: sql right join switching lhs and rhs

- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_arrange.py
Previously, sql queries like
```python
from siuba.data import cars_sql
from siuba import _, show_query, arrange
q = cars_sql >> arrange(-_.mpg) >> show_query()
```
```sql
SELECT cars.cyl, cars.mpg, cars.hp 
FROM cars ORDER BY -cars.mpg
```
Now it correctly uses DESC
```sql
SELECT cars.cyl, cars.mpg, cars.hp 
FROM cars ORDER BY cars.mpg DESC
```
(whether `-` should be used like this is still up for debate!)
> feat: pandas arrange supports grouped, sql supports minus for desc

- siuba/experimental/pivot/__init__.py
- siuba/experimental/pivot/test_pivot.py
Some tests are still failing (I kept `xfail` on those, and removed the decorator from others).
Essentially the ones that are failing are the ones that require `names_sep`, and `pivot_longer_spec`. I'm still missing 3 more tests until the `build_longer_spec` section, but will add them as we go along.
Current plan:
> [WIP] Switched pivot_longer to stack, and stubbed out some more tests

- siuba/tests/helpers.py
I think pandas v1 removed the ability to broadcast len 1 lists:
```
import pandas as pd
pd.DataFrame({'a': [1], 'b': [2,3]})   # error, unequal lens
```
> fix: data_frame helper, latest pandas no broadcast single item list

- .github/workflows/ci.yml
- siuba/sql/utils.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_summarize.py
addresses #321, #326. Note that sqlalchemy 1.4 is preparing for more API changes, so is issuing quite a few deprecation warnings. These shouldn't be an issue for now. I'm going to take another pass over to try and change all deprecated behaviors, then merge by EOW.
TODO:
> fix: basic sqlalchemy 1.4 compatibility

- docs/developer/sql-translators.ipynb
fixes an example in dev docs, where `track_call_windows`  became out of date.
> docs: fix broken example

- siuba/tests/conftest.py
- siuba/tests/helpers.py
* allows multiple bigquery test suites to run at the same time
* currently, it uses global-ish names for the tables
* this PR uses uuids and a table expiration to implement unique table names
> fix(ci): multiple bigquery test branches at the same time

- siuba/experimental/pd_groups/groupby.py
- siuba/experimental/pd_groups/test_pd_groups.py
Supports the use of aggregation calls like `n(_)` inside filter, that go GroupBy[DataFrame] -> GroupByAgg. Most operations take a GroupBy[Series], so I wrongly reached for the Series.name attribute.
```python
from siuba.data import mtcars
from siuba import _
from siuba.dply.vector import n
from siuba.experimental.pd_groups import fast_filter
mtcars >> fast_filter(n(_) > 1)
mtcars >> fast_filter(n(_.mpg) > 1)
```
> fix(pandas): fast methods support DataFrame aggs like n()

- setup.py
Addresses #336, #369
TODO:
edit: replicated install breaking on python 3.10.1 for Windows 10. `pip install git+https://github.com/machow/siuba.git@fix-install-encoding` worked, so going to merge!
> fix(install): correclty read utf-8 in readme on windows

- siuba/dply/verbs.py
Addresses #336 by replacing the __repr__ on DataFrameGroupBy, so it has a useful repr (similar to the DataFrame)
> feat(pandas): attach grouped repr method for console

- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_join.py
addresses #351 
* fixes pandas semi_join erroneously using a set rather than list when inferring on cols.
* sql semi_join now implements inferring on cols 
* tests of the behavior
> Fix semi_join inferring on arg

- .github/workflows/ci.yml
setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.
> Pin setup-gcloud to v0 instead of master

- .github/workflows/ci.yml
- pytest.ini
- siuba/sql/dialects/bigquery.py
- siuba/sql/dialects/sqlite.py
- siuba/sql/dply/vector.py
- siuba/tests/helpers.py
- siuba/tests/test_dply_series_methods.py
- siuba/tests/test_dply_vector.py
- siuba/tests/test_verb_arrange.py
- siuba/tests/test_verb_filter.py
- siuba/tests/test_verb_mutate.py
- siuba/tests/test_verb_summarize.py
This PR does the following:
* implements window functions (which sqlite started supporting a few years ago)
- includes dply vector functions. E.g. `dense_rank()`
* implements some aggs which I thought sqlite didn't support (e.g. `n()`)
* remove most cases of skipping sqlite from unit tests!
* fixes failing bigquery tests (that were accidentally skipped on CI)
> feat: support sqlite window functions

- siuba/sql/utils.py
- siuba/sql/verbs.py
- siuba/tests/test_sql_utils.py
Fixes issues with mock_sqlalchemy_engine:
* dialect parameter wasn't being used (every mock engine used postgresql dialect)
* collect on a LazyTbl using a mocked engine no longer errors. It now returns None.
See #407
> fix: mock_sqlalchemy_engine across dialects, collecting

- .github/workflows/ci.yml
- docker-compose.yml
- siuba/ops/utils.py
- siuba/siu/symbolic.py
- siuba/siu/visitors.py
- siuba/sql/dialects/base.py
- siuba/tests/helpers.py
- siuba/tests/test_dply_series_methods.py
- siuba/tests/test_siu.py
- siuba/tests/test_siu_symbolic.py
Addresses #399, by adding a dispatcher named array_ufunc, that is used in `Symbolic.__array_ufunc__`.
TODO:
* document (**edit*:* punting on this, will set aside a day for misc documentation tasks)
* ~~test array_ufunc concretes~~
* ~~verify that it will fail with SQL (but that defining a concrete method allows it to work!)~~
Example:
```python
from siuba.data import mtcars
from siuba import _, mutate, head
import numpy as np
res1 = mtcars >> mutate(res = _.hp - np.mean(_.hp))
res2 = mtcars >> mutate(res = _.hp - _.hp.mean())
res1.equals(res2)      # True
```
Here's what the symbolic looks like
```python
np.sqrt(_)
```
```
█─'__call__'
├─█─'__custom_func__'
│ └─<function array_ufunc at 0x106959310>
├─_
├─<ufunc 'sqrt'>
├─'__call__'
└─_
```
> feat: symbolic support numpy ufuncs

- siuba/siu/symbolic.py
- siuba/tests/test_siu_symbolic.py
I was a bit hasty with #415 -- this fixes, and adds additional tests of dispatchers, including multiple cases of calling numpy functions, and numpy functions on numpy functions.
> fix: correctly dispatch array_function

- siuba/siu/visitors.py
- siuba/sql/__init__.py
- siuba/sql/translate.py
- siuba/sql/verbs.py
- siuba/tests/test_sql_verbs.py
- siuba/tests/test_verb_group_by.py
* Rewrites track_call_windows from using a visitor class, to being a simple function (the visiting was unnecessary, and had the undesired effect of repeating windows that were components of a larger expression in the inner select)
* Moves LazyTbl.shape_call() logic to be a method on the SqlTranslator class
> Feat sql over

- .github/workflows/ci.yml
- siuba/ops/support/base.py
- siuba/sql/dialects/_dt_generics.py
- siuba/sql/dialects/base.py
- siuba/sql/dialects/duckdb.py
- siuba/sql/dialects/postgresql.py
- siuba/sql/dply/vector.py
- siuba/sql/utils.py
- siuba/sql/verbs.py
- siuba/tests/conftest.py
- siuba/tests/helpers.py
- siuba/tests/test_sql_misc.py
- siuba/tests/test_sql_verbs.py
- siuba/tests/test_verb_count.py
re-implementation of #380
Notes:
* This requires the code on master of https://github.com/Mause/duckdb_engine.
* Contains a patch to fix the issue in #380 of literal ints being interpreted as strings. Basically, for duckdb we bind literals when executing the query, so that there are no parameters. Once https://github.com/duckdb/duckdb/issues/2972 is released, can remove the patch.
Edit: Updated notes (May 30th):
* Breaking: LazyTbl now gets the dialect name from sqlalchemy's URL, to work around needing dialects to set the correct name. This means LazyTbl must take an Engine, not a connection (which seems weird to pass it anyway).
* I added a temporary `_is_dialect_duckdb` function to handle these edge cases:
- `collect()` uses duckdb's query(...).to_df() method
- `collect()` binds …
> feat: duckdb support

- .readthedocs.yaml
- docs/api_table_core/01_filter.Rmd
- docs/index.rst
Note that this PR also 
* fixes the docs build on readthedocs
* removes the in-progress dev API
Thanks to Chelsea Parlett-Pelleriti for the suggestion!
> document using an OR condition in filter

- siuba/tests/helpers.py
* removes the use of reflection when loading data for snowflake tests
The problem what that snowflake sqlalchemy getting the columns of a table was taking ~10s. Below is an example query it would generate:
```sql
SELECT /* sqlalchemy:_get_schema_columns */
ic.table_name,
ic.column_name,
ic.data_type,
ic.character_maximum_length,
ic.numeric_precision,
ic.numeric_scale,
ic.is_nullable,
ic.column_default,
ic.is_identity,
ic.comment
FROM information_schema.columns ic
WHERE ic.table_schema='TESTS'
ORDER BY ic.ordinal_position
```
(note that this may be related to the number of tables in our database? or could be improved somehow? idk)
> tests: speed snowflake tests by removing reflection

- siuba/dply/verbs.py
- siuba/tests/test_verb_case_when.py
Addresses issue using fillna mentioned in https://github.com/machow/siuba/issues/431
* if_else and case_when now return a Series (rather than numpy array)
> fix!: if_else and case_when now return Series

- siuba/dply/forcats.py
- siuba/tests/test_dply_forcats.py
* implements fct_infreq, which returns a categorical w/ categories ordered by frequency counts (highest first).
* implements fct_inorder, which returns a categorical w/ categories in observed-order (first seen first).
* cleans up existing docstrings, formats into numpydoc style.
> forcats functions: fct_inseq, fct_infreq

- examples/examples-siu.ipynb
- siuba/siu/__init__.py
- siuba/siu/calls.py
- siuba/siu/dispatchers.py
- siuba/siu/symbolic.py
- siuba/tests/test_siu.py
- siuba/tests/test_siu_dispatchers.py
- siuba/tests/test_verb_utils.py
This PR expands the `pipe` function, and adds a `call()` function, to allow...
* pipe() for a manual version of making pipes w/ `>>`
* `call()` for making a specific step of pipe
* arbitrary `*args` and `**kwargs`
* a siu expression allowed as the first argument, rather than a regular callable
* the ability choose where the data should go in the call
* **Pipeable() is now deprecated.**
Note that this means that the old `pipe()` was essentially renamed `call()`. Because `pipe()` had very limited behavior, **these changes are fully backwards compatible**.
Should address #246 #408 #207. See #47 for a docs related issue.
> ⚠️ **TODO**: Note that I still need to add support for things like `call(mutate, _, a = _.x + 1)`. Going to release as-is, though, since functions like mutate can already …
> feat(siu): allow pipe func to accept args and kwargs

- .github/workflows/ci.yml
- pytest.ini
- siuba/dply/forcats.py
- siuba/dply/verbs.py
- siuba/experimental/datetime.py
* Fills out docstrings for a dply verbs
* Cleans up docstrings in various vector functions
* Ensures everything uses numpydoc style docstrings
* Adds lots of examples that run using doctest
> docs: complete docstrings for all verbs

- siuba/tests/test_sql_misc.py
Quick fix. A test (which is actual testing that an error is raised) began failing due to a change in exception types thrown by duckdb.
> tests(sql): update failing test, due to duckdb change

- siuba/experimental/completer.py
* Wraps the _jedi_matches function from IPython, rather than vendoring it.
* Now sorts results so column names are first.
TODO: ~~validate this works on vscode (from pairing, it looks like it doesn't)~~ works, see comment below
> feat(experimental): fix tab completions

- siuba/dply/verbs.py
- siuba/siu/_databackend.py
- siuba/sql/verbs.py
Adds the `dplyr::tbl` function, with support for pandas and sqlalchemy.
TODO:
> feat(tbl): add tbl function for pandas and sqla

- siuba/dply/verbs.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_group_by.py
This PR addresses dply verbs not having support for DataFrameGroupBy
* #443 
* (todo) #404 
* #118 
* #257 
* adds tests of group_by preceeding many verbs
> fix(pandas): ensure verbs accept DataFrameGroupBy

- siuba/data/__init__.py
Currently `from siuba.data import cars_sql` is missing a return statement. Quick fix to resolve.
> fix(data): correctly return sql cars data

- siuba/dply/verbs.py
- siuba/tests/test_verb_spread.py
This PR fixes gather to behave more like in dplyr:
* gather now will gather everything if no selections are specified (addresses #448)
* gather with grouped data attempts to re-apply any group keys remaining in the result:
- group keys still in result data are kept
- the measure or value var are not considered when re-applying a key
- if no group keys can be re-applied, an ungrouped DataFrame is returned
> fix(pandas): gather default selection is all columns

- siuba/dply/verbs.py
- siuba/sql/utils.py
- siuba/sql/verbs.py
- siuba/tests/test_verb_show_query.py
Addresses https://github.com/machow/siuba/issues/346 for simplifying sql queries. The main issue was that siuba's LazyTbl was starting each query out using a full select statement, rather than just the sqlalchemy table object.
The original reason for always using select statements is that in sqlalchemy select statements can do more (e.g. have a `with_only_columns` method) than table objects (which mostly go in from clauses, are used to start select statements, have columns).
This PR adds a new property `last_select` to complement `last_op`. If `last_op` would return a table, then `last_select` will make it a select statement. This allows verbs that e.g. use `with_only_columns` to ensure they get a select statement.
```python
from siuba.data import cars_sql
from siuba import _, inner_join, …
```
> feat(sql): add LazyTbl.last_select to simplify queries

- .github/workflows/ci.yml
This PR removes publishing siuba docs from this repo, as they are now generated on [machow/siuba.org](https://github.com/machow/siuba.org)
> ci: remove doc publishing

- siuba/dply/verbs.py
- siuba/sql/across.py
- siuba/tests/test_verb_across.py
This PR provides two fixes for `across()`
* fix(sql): `across()` now currently sets the OVER clause when LazyTbl is grouped.
* fix(pandas): `across()` now correctly handles aggregates inside a mutate. Previously, it was screwing up the placement of the result by assigning using the index, and not broadcasting.
```python
from siuba.data import cars
from siuba import across, Fx, mutate, head
cars.groupby("cyl") >> mutate(across(_[_.hp, _.mpg], Fx.mean())) >> head()
```
```
cyl        mpg          hp
0    6  19.742857  122.285714
1    6  19.742857  122.285714
2    4  26.663636   82.636364
3    6  19.742857  122.285714
4    8  15.100000  209.214286
```
> fix: across handles sql grouped; handles pandas mutate with aggs

- siuba/dply/verbs.py
- siuba/tests/test_sql_misc.py
- siuba/tests/test_verb_mutate.py
- siuba/tests/test_verb_summarize.py
Addresses #458, #251 by..
* setting `dropna=False, group_keys=True` in group_by.
* having summarize regroup with those arguments if necessary.
* note that mutate sets `group_keys=False` to ensure group columns aren't put on the result twice.
> fix: summarize raising error when a grouping col is all NA (or mostly NA)

- .github/workflows/ci.yml
- Makefile
- requirements.txt
- setup.py
- siuba/dply/verbs.py
- siuba/experimental/pivot/sql_pivot_wide.py
- siuba/ops/support/base.py
- siuba/sql/across.py
- siuba/sql/backend.py
- siuba/sql/dialects/base.py
- siuba/sql/dialects/duckdb.py
- siuba/sql/dialects/sqlite.py
- siuba/sql/dply/vector.py
- siuba/sql/translate.py
- siuba/sql/utils.py
- siuba/sql/verbs/arrange.py
- siuba/sql/verbs/conditional.py
- siuba/sql/verbs/filter.py
- siuba/sql/verbs/mutate.py
- siuba/sql/verbs/select.py
- siuba/tests/helpers.py
- siuba/tests/test_dply_series_methods.py
- siuba/tests/test_dply_vector.py
- siuba/tests/test_sql_verbs.py
This PR adjusts sqlalchemy imports to work with v2.0. Most of the structure for backwards compat was already in place, so this is hopefully just a few imports.
> fix(sql): sqlalchemy 2.0 compat imports
